### ISSUE TITLE
Doubt about the tool

### ISSUE THREAD

**Issue by cairoapcampos** [schorschii/LAPS4LINUX#22]
I recently heard about Microsoft LAPS. What is the difference between Microsoft LAPS and LAPS4LINUX?

The problem I have today is that when a person leaves the Information Technology sector, the local password for Windows machines is not changed.

With LAPS4LINUX is it possible to set a local password for all machines in a domain when a person leaves the company? That would already help me a lot. I don't need a different password on each machine.

**Comment by schorschii** [comment]
Please have a look at the Readme, most general questions are answered there.

LAPS4LINUX is an unofficial Linux and macOS implementation of the Local Administrator Password Solution (LAPS) from Microsoft. The management client is also executable under Windows and provides additional features (e.g. display additional LDAP values).

LAPS(4LINUX) will periodically change your local administrator passwords (not only when someone leaves the company).

What do you mean with "I don't need a different password on each machine."? That's exactly what LAPS does since it generates random passwords.

**Comment by cairoapcampos** [comment]
I understood. Thanks.
