### ISSUE TITLE
macOS 13.5 - NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by tlcarpenter** [schorschii/LAPS4LINUX#23]
I installed the LAPS4LINUX client on an Mac mini (M2 Pro) running macOS 13.5; I get the notification below after entering a domain username and password for the search.

![Screenshot 2023-08-15 at 9 32 24 AM](https://github.com/schorschii/LAPS4LINUX/assets/727537/eb9d3ad5-9a48-4b80-96ba-f15847ce7c90)

Using the same inputs for laps-cli the following is displayed

urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
LAPS4LINUX CLI v1.7.0

I've found a number of similar reports online with various solutions, e.g.

https://stackoverflow.com/questions/76187256/importerror-urllib3-v2-0-only-supports-openssl-1-1-1-currently-the-ssl-modu

but I'm not sure what the simplest, most secure solution is.

**Comment by schorschii** [comment]
Do you use the installation package from [here](https://github.com/siebersystems/BinaryPackages)? If not, can you please test it with this?
Which macOS version are you using? Which certificate authority (CA) is used for signing your LDAP server's certificate? You can find it with `openssl s_client -connect <ADDRESS>:636`.

**Comment by tlcarpenter** [comment]
I am using the package you linked to above. Version of macOS is 13.5. Cert is self-signed; I'll try importing it to the System keychain and see what happens.

**Comment by tlcarpenter** [comment]
Importing the cert and marking it as 'trusted' eliminated the notification displayed when executing a search by the GUI client. Executing a search with laps-cli still displays the same error mentioned above (urllib3/init.py:34: NotOpenSSLWarning:...) but the authentication succeeds and returns information from AD for the host that was searched.

**Comment by tlcarpenter** [comment]
Update to earlier information: I was confused about the cert I imported to macOS' System keychain - it was actually the cert of our local CA I imported not the certs of any of the AD DCs (whose certs are signed by our local CA and that the LAPS4LINUX client would have been sent when executing a search).

**Comment by schorschii** [comment]
Sorry for the delay, I'm back again. Thanks for clarifying that the server cert is self-signed. The error is an intentional security feature in this case. Good to hear that the message disappears after importing the cert into the macOS keychain. I didn't tested this scenario but this is the expected behavior.

To answer your initial question: yes, this is the most secure solution for self-signed certs since the alternative is to completely disable transport encryption in the LAPS client config file.

The `NotOpenSSLWarning` can be ignored here. It is thrown by the `dnspython` import, which imports `requests` and requests uses `urllib3`. It does not affect the actual LDAP connection.
