### ISSUE TITLE
Laps4Linux-Runner DEB Build: cron job not marked as executable

### ISSUE THREAD

**Issue by fraunhofer-ipm-itk** [schorschii/LAPS4LINUX#33]
Hi,
I believe I have found a problem with the build script for the deb and the resulting package.
The rpm might also be affected, however, I haven't tested that yet. 
## Problem
The password does not rotate automatically. (At least on some of our machines)
## Cause
When installed, the cron job under /etc/cron.hourly is not marked a executable.
This means that the cron job cannot be executed, at least under Ubuntu.
You can confirm that by runnning `run-parts --test /etc/cron.hourly/`. It doesn't show the path `/etc/cron.hourly//laps-runner`.
However, if you mark the job as executable, by running `chmod +x /etc/cron.hourly/laps-runner`, it does.
## Steps to reproduce
Tested under Ubuntu 24.04:
1. Build and Install the Package
2. Configure and Test
3. (optional) mark the password as expired
4. (optional) wait an hour
5. Password does not automatically renew itself
## Solution
Make the cron job executable, by replacing the line in the build script with something like this:
`install -D -m 755 ../../assets/laps-runner.cron              $BUILDDIR/etc/cron.hourly/laps-runner`

I hope this helps.
Kind regards,
Simon

**Comment by schorschii** [comment]
Thanks Simon, you're right. I'll fix the issue and create a new release. It was introduced with the automated Github builds since v1.8.0. I'm annoyed that I didn't notice myself; I have currently pretty old versions in use on my machines, I need to change this now too.

The rpm package is not affected because it contains this line:
https://github.com/schorschii/LAPS4LINUX/blob/fa976092735153a2954ed3c86e098cedf1309609/installer/rpm/build.sh#L43
